CREATE TABLE IF NOT EXISTS sa_coffee_shop_cash_sales.src_coffee_shop_cash (
	transaction_id VARCHAR(255),
	transaction_date VARCHAR(255),
	transaction_time VARCHAR(255),
	quantity_sold VARCHAR(255),
	discount_amount VARCHAR(255),
	sales VARCHAR(255),
	payment_id VARCHAR(255),
	payment_method VARCHAR(255),
	product_price VARCHAR(255),
	product_size VARCHAR(255),
	product_id VARCHAR(255),
	product_title VARCHAR(255),
	product_category VARCHAR(255),
	product_description VARCHAR(255),
	store_id VARCHAR(255),
	store_description VARCHAR(255),
	store_city VARCHAR(255),
	store_address VARCHAR(255),
	store_manager_id VARCHAR(255),
	store_manager_first_name VARCHAR(255),
	store_manager_last_name VARCHAR(255),
	store_manager_passport_id VARCHAR(255),
	store_manager_city VARCHAR(255),
	store_manager_address VARCHAR(255),
	store_manager_phone_number VARCHAR(255),
	employee_id VARCHAR(255),
	employee_first_name VARCHAR(255),
	employee_last_name VARCHAR(255),
	employee_passport_id VARCHAR(255),
	employee_position VARCHAR(255),
	employee_city VARCHAR(255),
	employee_address VARCHAR(255),
	employee_phone_number VARCHAR(255),
	customer_id VARCHAR(255),
	customer_first_name VARCHAR(255),
	customer_last_name VARCHAR(255),
	customer_email VARCHAR(255),
	customer_phone_number VARCHAR(255)
);

MERGE INTO sa_coffee_shop_cash_sales.src_coffee_shop_cash src
	
USING sa_coffee_shop_cash_sales.ext_coffee_shop_cash ext
ON ext.transaction_id = src.transaction_id AND ext.product_id = src.product_id

WHEN NOT MATCHED THEN
	INSERT VALUES(  transaction_id,
					transaction_date,
					transaction_time,
					quantity_sold,
					discount_amount,
					sales,
					payment_id,
					payment_method,
					product_price,
					product_size,
					product_id,
					product_title,
					product_category,
					product_description,
					store_id,
					store_description,
					store_city,
					store_address,
					store_manager_id,
					store_manager_first_name,
					store_manager_last_name,
					store_manager_passport_id,
					store_manager_city,
					store_manager_address,
					store_manager_phone_number,
					employee_id,
					employee_first_name,
					employee_last_name,
					employee_passport_id,
					employee_position,
					employee_city,
					employee_address,
					employee_phone_number,
					customer_id,
					customer_first_name,
					customer_last_name,
					customer_email,
					customer_phone_namber)
WHEN MATCHED THEN
    UPDATE 
	SET	    product_price = ext.product_price,
			product_size = ext.product_size,
			product_title = ext.product_title,
			product_category = ext.product_category,
			product_description = ext.product_description;